---
-
  name: This playbook is for my webserver
  hosts: localhost
  connection: local

  tasks:
    -
      name: Installing webserver package
      yum:
        name: httpd
        state: present

    -
      name: Configuring webserver file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This page has been created using the Power of Ansible Automation</h1>"

    -
      name: Start webserver application
      service:
        name: httpd
        state: started
        enabled: yes
